### PR TITLE
Edited Person class and Edited SampleDataUtil

### PR DESCRIPTION
**Pull request by Bahamas20**
Supplier package has necessary classes like Supplier,Name,Contact,Price,Item and Address
SamepleDataUtil has sample data for supplier list

### CODE REVIEW

**Comment by Bahamas20** [comment]
Cannot merge as Storage and UI portion still working on it

**Comment by hauchongtang** [comment]
> Cannot merge as Storage and UI portion still working on it 

Ok can mark as draft PR then un draft it after u done 👍🏼

**Comment by hauchongtang** [comment]
@Bahamas20 Acutally the Supplier don't need to create new Supplier class, just Rename Person as a supplier in the code.

**Comment by hauchongtang** [comment]
Analogy is Person's name, contact, address attributes are the same as Supplier. Having another Supplier class will require extending a new storage (possibly) which can be more tedious.

**Comment by Bahamas20** [comment]
Instead of new Supplier Class , adapted current Person class to take in Price of supplied item and Item name and Email attribute removed

Screenshot 2022-10-08 at 11 21 13 PM

**Comment by Bahamas20** [comment]
Test cases have yet to be changed to accomdate newer version of Person class

**Comment by hauchongtang** [comment]
@Bahamas20 can run `./gradlew checkStyleMain` and `./gradlew checkStyleTest` in intellij terminal to check for style errors.

**Pull request closed without merging**
